/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.locadorabsl.telas;

import br.com.locadorabsl.dao.ClienteDAO;
import br.com.locadorabsl.models.Cliente;
import com.sun.glass.events.KeyEvent;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aluno
 */
public class TelaBuscaClientes extends javax.swing.JInternalFrame {

    ArrayList<Cliente> clientes = new ArrayList();
    private DefaultTableModel modelo = new DefaultTableModel();
    
    /**
     * Creates new form TelaBuscaClientes
     */
    public TelaBuscaClientes() {
        initComponents();
        modelo.addColumn("ID");
        modelo.addColumn("CPF");
        modelo.addColumn("Nome");
        modelo.addColumn("Endereço");
        modelo.addColumn("Telefone");
        modelo.addColumn("CNH");
        TblBusCli.setModel(modelo);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TblBusCli = new javax.swing.JTable();
        TxtBusCli = new javax.swing.JTextField();
        BtnBusCli = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        CmbBusCli = new javax.swing.JComboBox<>();

        TblBusCli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "CPF", "Nome", "Endereço", "Telefone", "CNH"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TblBusCli);
        if (TblBusCli.getColumnModel().getColumnCount() > 0) {
            TblBusCli.getColumnModel().getColumn(0).setResizable(false);
            TblBusCli.getColumnModel().getColumn(0).setPreferredWidth(1);
            TblBusCli.getColumnModel().getColumn(1).setResizable(false);
            TblBusCli.getColumnModel().getColumn(2).setResizable(false);
            TblBusCli.getColumnModel().getColumn(3).setResizable(false);
            TblBusCli.getColumnModel().getColumn(4).setResizable(false);
            TblBusCli.getColumnModel().getColumn(5).setResizable(false);
        }

        TxtBusCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtBusCliKeyPressed(evt);
            }
        });

        BtnBusCli.setText("Selecionar");

        jLabel1.setText("Busca de Clientes");

        CmbBusCli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CPF", "Nome", "CNH" }));
        CmbBusCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbBusCliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnBusCli)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(290, 290, 290)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(148, 148, 148)
                            .addComponent(CmbBusCli, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(TxtBusCli, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtBusCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CmbBusCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnBusCli)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CmbBusCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbBusCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbBusCliActionPerformed

    private void TxtBusCliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtBusCliKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        if(key == KeyEvent.VK_ENTER){
        ClienteDAO dao = new ClienteDAO();
        clientes= new ArrayList();
        clientes = (ArrayList<Cliente>) dao.pesquisarNome(TxtBusCli.getText(), CmbBusCli.getSelectedItem().toString());
        for (Cliente c: clientes){
            this.modelo.addRow(new Object[]{ c.getId_cliente(), c.getCpf(), c.getNome(), c.getEndereco(), c.getTelefone(), c.getCnh() });
        }
        
        }
        
        
    }//GEN-LAST:event_TxtBusCliKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBusCli;
    private javax.swing.JComboBox<String> CmbBusCli;
    private javax.swing.JTable TblBusCli;
    private javax.swing.JTextField TxtBusCli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
