/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.locadorabsl.telas;

import br.com.locadorabsl.dao.LocacaoDAO;
import br.com.locadorabsl.models.Locacao;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Algo
 */
public class TelaBuscaLocacao extends javax.swing.JFrame {

     List<Locacao> locacoes = new ArrayList<>();
     private DefaultTableModel modelo = new DefaultTableModel();
    /**
     * Creates new form TelaBuscaLocacao
     */
    public TelaBuscaLocacao() {
        initComponents();
        modelo.addColumn("ID");
        modelo.addColumn("CPF");
        modelo.addColumn("Veículo");
        modelo.addColumn("Período");
        modelo.addColumn("Valor");
        modelo.addColumn("Funcionário");
        TblBusLoc.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TblBusLoc = new javax.swing.JTable();
        BtnBusLoc = new javax.swing.JButton();
        TxtBusLoc = new javax.swing.JTextField();
        CmbBusLoc = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TblBusLoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "CPF", "Veículo", "Período", "Valor", "Funcionário"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Float.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TblBusLoc);
        if (TblBusLoc.getColumnModel().getColumnCount() > 0) {
            TblBusLoc.getColumnModel().getColumn(0).setResizable(false);
            TblBusLoc.getColumnModel().getColumn(0).setPreferredWidth(1);
            TblBusLoc.getColumnModel().getColumn(1).setResizable(false);
            TblBusLoc.getColumnModel().getColumn(2).setResizable(false);
            TblBusLoc.getColumnModel().getColumn(4).setResizable(false);
            TblBusLoc.getColumnModel().getColumn(5).setResizable(false);
        }

        BtnBusLoc.setText("Selecionar");
        BtnBusLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBusLocActionPerformed(evt);
            }
        });

        TxtBusLoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtBusLocKeyPressed(evt);
            }
        });

        CmbBusLoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CPF", "Veículo" }));

        jLabel1.setText("Busca de Locações");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(CmbBusLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(TxtBusLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(BtnBusLoc)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(60, 60, 60)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(235, 235, 235))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtBusLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CmbBusLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnBusLoc)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtBusLocKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtBusLocKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        if(key == KeyEvent.VK_ENTER){
        this.modelo.setNumRows(0);    
        LocacaoDAO dao = new LocacaoDAO();
        locacoes = new ArrayList();
        locacoes = (ArrayList<Locacao>) dao.pesquisarLocacao(TxtBusLoc.getText(), CmbBusLoc.getSelectedItem().toString());
        for (Locacao c: locacoes){
            this.modelo.addRow(new Object[]{ c.getId_locacao(), c.getCpf_cliente(), c.getVeiculo(), c.getPeriodo(), c.getValor(), c.getFuncionario()});
        }
        }
    }//GEN-LAST:event_TxtBusLocKeyPressed

    private void BtnBusLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBusLocActionPerformed
        // TODO add your handling code here:
        int row = TblBusLoc.getSelectedRow();
        TelaLocacao.locIdSelecionado(locacoes.get(row).getId_locacao());
        TelaLocacao.veiculoSelecionado(locacoes.get(row).getVeiculo());
        TelaLocacao.clienteSelecionado(locacoes.get(row).getCpf_cliente());
        TelaLocacao.periodoSelecionado(locacoes.get(row).getPeriodo());
        TelaLocacao.valorSelecionado(locacoes.get(row).getValor());
        TelaLocacao.funcionarioSelecionado(locacoes.get(row).getFuncionario());
        this.dispose();
    }//GEN-LAST:event_BtnBusLocActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBuscaLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBuscaLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBuscaLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBuscaLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaBuscaLocacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBusLoc;
    private javax.swing.JComboBox<String> CmbBusLoc;
    private javax.swing.JTable TblBusLoc;
    private javax.swing.JTextField TxtBusLoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
